version: "3"
services:
  minio:
    image: "minio/minio:latest"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["server", "/data/minio", "--console-address", ":9001"]
    volumes:
      - minio_data:/data/minio
volumes:
  minio_data:

